server:
  port: 8082


management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/zipkin/



logging:
 file:
   path: C:\Users\USER\Downloads\logs\microservice.logs